linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(github.com/spf13/viper)

linters:
    disable-all: true
    enable:
        - gofmt
        # - gofumpt
        - staticcheck

issues:
    exclude-dirs:
        - gcsfs/internal/stiface
