sudo: false
language: go

go:
  - "1.13"
  - "1.14"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go build -v ./...
  - go test -count=1 -cover -race -v ./...

